### ISSUE TITLE
Should this also include navbar like on shopify dashboard page?

### ISSUE THREAD

**Issue by azamuddin** [ablesense/bootstrap-polaris#2]
I know the navigation bar is not included in the polaris design system. But if we want the complete look like shopify, I think navigation bar is needed to. Can we create that too here?

**Comment by derekmorash** [comment]
You could use this along with your own css for the navigation bar. You could include the bootstrap-polaris css in your project or fork the repo and create your own components in it for your needs.

That likely isn't something that will be included in this project though, this is just trying to recreate shopify polaris for embedded apps.

**Comment by azamuddin** [comment]
Alright, I think yes, that should be it.
