### ISSUE TITLE
Update to the latest bootstrap

### ISSUE THREAD

**Issue by tirsolecointere** [ablesense/bootstrap-polaris#3]
I want to replace oficial bootstrap 4.1.3 with this bootstrap-polaris in my project but it mess things up. Seems like this one doesn't include all the bootstrap utilities and stuff that the oficial 4.1.3 has.

**Comment by derekmorash** [comment]
You're right it doesn't include a lot of things from bootstrap. This project was build using bootstrap as just a base framework to recreate some of the main components from Shopify Polaris. This isn't intended as a direct replacement for Bootstrap. This available components that have been tested can be seen here https://ablesense.github.io/bootstrap-polaris/demo/index.html

This project was originally meant as an internal project to help us build Shopify apps while maintaining clean semantic markup and without being tied to using React.

This isn't a theme sitting on top of bootstrap but rather a forked an modified version, this makes updating bootstrap versions not very easy. It might seem like a drawback but for the intended purpose of the project this is fine.

I hope this clears things up!
